import Head from 'next/head'
import styled from 'styled-components'
import Container from '../components/Container/Container'

export default function Home() {
  return (
    <>
      <Head>
        <title>Spacetagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledWrapper>
        <Container>
          <StyledTitle>spacetagram</StyledTitle>
        </Container>
      </StyledWrapper>
    </>
  )
}


// STYLES
const StyledWrapper = styled.div`

`

const StyledTitle = styled.h1`
  font-family: var(--font-stack-2);
  text-align: center;
`
